version: "2.3"

services:
  nginx:
    build:
      context: ./nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    tty: true
    ports:
      - 80:80