version: "2.3"

# networks:
#   no-internet:
#     driver: bridge
#     internal: true

services:
  nginx:
    build: ./nginx
    expose:
      - '80'
  
  test:
    image: tutum/curl
    tty: true

  
  # test-site1-upstream:
  
  # test-site2-upstream:
  
  # tests: